In [1]:
import pandas as pd
import numpy as np

In [2]:
file_path = './data/final_behavior_hmm_result_n_states3.xlsx'

# Excel 파일 불러오기
xls = pd.ExcelFile(file_path)

# 시트 이름 확인
sheet_names = xls.sheet_names
print(sheet_names)  # 시트 이름 출력

# 각 시트를 데이터프레임으로 저장
dfs = {}  # 데이터프레임을 저장할 딕셔너리

for sheet_name in sheet_names:
    df = xls.parse(sheet_name)  # 시트 불러오기
    dfs[sheet_name] = df  # 데이터프레임을 딕셔너리에 저장

['state0', 'state1', 'state2']

In [3]:
dfs['state0']

,code,duration,A/C,M/F,predicted_engagement_levels
0,"['Approach', 'None', 'Approach', 'Touch', 'Non...","[12160, 5520, 3120, 3280, 3840, 4960]",Adult,Female,state0
1,"['Approach', 'None', 'None', 'Approach', 'None...","[8160, 34160, 15280, 2560, 15200, 1280, 2960, ...",Adult,Female,state0
2,"['Approach', 'None', 'Touch', 'None', 'Gesture...","[9760, 14480, 13840, 7520, 9520, 8800, 15280, ...",Child,Female,state0
3,"['Approach', 'Gesture', 'None', 'Gesture', 'To...","[8080, 1760, 2560, 2320, 3040, 16160, 5680, 43...",Child,Female,state0
4,"['Approach', 'Gesture', 'None']","[8480, 5160, 77440]",Adult,Male,state0
...,...,...,...,...,...
101,"['Approach', 'Touch', 'None', 'Touch', 'None',...","[4880, 2240, 1040, 24000, 480, 2160, 1760, 384...",Child,Male,state0
102,"['Approach', 'None', 'Approach', 'None', 'Touc...","[4960, 2160, 2160, 22720, 3120, 720, 34080, 13...",Child,Male,state0
103,"['Avoid', 'None', 'Approach', 'Gesture', 'Gest...","[5360, 18000, 8320, 2880, 3440, 0]",Child,Male,state0
104,"['Approach', 'None', 'Gesture', 'None', 'Appro...","[3600, 18640, 2640, 2960, 4560, 13680, 2960, 1...",Child,Male,state0
105,"['Approach', 'Touch', 'None', 'Touch', 'None']","[6080, 10960, 9920, 2320, 16640]",Child,Male,state0

In [4]:
dfs['state1']

,code,duration,A/C,M/F,predicted_engagement_levels
0,"['Approach', 'None']","[2720, 2960]",Child,Female,state1
1,"['Approach', 'None']","[5520, 6320]",Child,Female,state1
2,"['Approach', 'None', 'Approach', 'None']","[9240, 15600, 5920, 6360]",Child,Male,state1
3,"['Approach', 'None']","[4160, 7760]",Child,Male,state1
4,"['Approach', 'None', 'Approach', 'None']","[8640, 16480, 6000, 6640]",Adult,Female,state1
...,...,...,...,...,...
332,"['Approach', 'None']","[6800, 9520]",Child,Male,state1
333,"['Approach', 'None', 'Approach', 'None']","[6080, 33520, 2160, 10000]",Adult,Female,state1
334,"['Approach', 'None']","[9760, 135360]",Child,Female,state1
335,"['Approach', 'None', 'Approach', 'None', 'Appr...","[10400, 6560, 5280, 5200, 4560, 20800]",Child,Female,state1
336,"['Approach', 'Touch']","[12640, 4800]",Child,Male,state1

In [5]:
dfs['state2']

,code,duration,A/C,M/F,predicted_engagement_levels
0,"['Approach', 'None', 'Touch', 'None', 'Touch',...","[10000, 1600, 2320, 11120, 2560, 29520, 12240]",Child,Female,state2
1,"['Approach', 'Avoid', 'Follow', 'Avoid', 'Appr...","[4080, 6240, 10480, 4560, 12800, 5200, 7120, 2...",Child,Female,state2
2,"['Approach', 'None', 'Touch', 'None', 'Touch',...","[2320, 11200, 5440, 2720, 6000, 2400, 3680, 61...",Child,Female,state2
3,"['Approach', 'None', 'Gesture', 'None', 'Gestu...","[3600, 2640, 7440, 3040, 3240]",Child,Male,state2
4,"['Approach', 'None', 'Gesture', 'None', 'Appro...","[10640, 10800, 7840, 10000, 5120, 11080, 4000,...",Child,Male,state2
5,"['Approach', 'None', 'Gesture', 'None', 'Touch...","[5680, 2880, 7280, 53920, 4400, 30480, 2400, 2...",Child,Male,state2
6,"['Approach', 'Avoid', 'Follow']","[3920, 3520, 24480]",Child,Male,state2
7,"['Approach', 'Avoid']","[2160, 17200]",Child,Male,state2
8,"['Approach', 'None', 'Approach', 'None', 'Appr...","[34160, 2960, 4800, 20560, 3600, 3440, 8800, 1...",Child,Female,state2
9,"['Approach', 'Touch', 'Touch', 'None', 'Touch'...","[6160, 6560, 134880, 5680, 10240, 3200, 2800, ...",Child,Female,state2
10,"['Approach', 'Approach', 'Touch', 'None']","[2880, 5600, 44880, 9120]",Child,Male,state2
11,"['Approach', 'None', 'Touch', 'None', 'Touch',...","[10880, 1200, 2400, 880, 2320, 14880, 3840, 11...",Adult,Male,state2
12,"['Approach', 'None', 'Touch', 'None', 'Approac...","[3680, 12480, 3760, 5680, 3360, 8400, 9120]",Child,Male,state2
13,"['Approach', 'Avoid', 'Follow']","[3040, 4640, 15440]",Child,Female,state2
14,"['Approach', 'None', 'Gesture', 'None', 'Gestu...","[7440, 21040, 4240, 1920, 3760, 2080, 3280, 26...",Adult,Male,state2
15,"['Approach', 'None', 'Touch', 'None', 'Touch',...","[4400, 1600, 2800, 880, 3920, 19680, 1280, 648...",Child,Male,state2
16,"['Approach', 'None', 'Gesture', 'None', 'Gestu...","[2960, 1440, 6240, 5200, 8440]",Child,Male,state2
17,"['Approach', 'None', 'Approach', 'None', 'Appr...","[5520, 15920, 2160, 12240, 4720, 27360, 2160, ...",Adult,Male,state2
18,"['Approach', 'None', 'Approach', 'None', 'Touc...","[5440, 155200, 5360, 3280, 3040, 1920, 6720, 5...",Child,Female,state2
19,"['Approach', 'None', 'Touch', 'None', 'Touch',...","[16320, 13600, 6240, 13760, 9360, 3360, 1920, ...",Adult,Male,state2
20,"['Approach', 'None', 'Approach', 'None', 'Touc...","[8800, 25440, 3760, 4160, 2000, 12320, 3360, 6...",Adult,Male,state2
21,"['Approach', 'None', 'Touch', 'None', 'Touch',...","[13040, 7520, 2160, 15360, 3440, 12880, 12440,...",Adult,Male,state2
22,"['Approach', 'None', 'Touch', 'None', 'Touch',...","[13520, 12720, 3120, 13280, 1840, 2000, 4160, ...",Adult,Male,state2
23,"['Approach', 'None', 'Gesture', 'None', 'Gestu...","[6800, 2560, 2080, 5840, 2720, 12480]",Adult,Female,state2
24,"['Approach', 'None', 'Approach', 'None', 'Touc...","[4000, 3760, 2720, 10720, 8480, 7120, 2480]",Child,Male,state2
25,"['Approach', 'None', 'Touch', 'None', 'Touch',...","[7600, 1600, 2240, 5280, 5680, 3840, 2240, 34720]",Child,Male,state2
26,"['Approach', 'None', 'Gesture', 'None', 'Gestu...","[4080, 2800, 2880, 4160, 2080, 880, 3360, 2240...",Child,Male,state2
27,"['Approach', 'None', 'Touch', 'None', 'Touch',...","[15920, 12640, 4960, 10560, 7680, 15280, 4320,...",Adult,Female,state2
28,"['Approach', 'None', 'Approach', 'None', 'Touc...","[9040, 1920, 2240, 3160, 1840, 20320, 2800, 29...",Child,Male,state2
29,"['Approach', 'None', 'Approach', 'None', 'Appr...","[3200, 3680, 3840, 12480, 2240, 1920, 21120, 2...",Adult,Male,state2
30,"['Approach', 'None', 'Touch', 'None', 'Touch',...","[9600, 31600, 3680, 42240, 2560, 8400, 6560, 2...",Child,Male,state2
31,"['Approach', 'None', 'Approach', 'None', 'Appr...","[11360, 12480, 5120, 2960, 3360, 21040, 4160, ...",Adult,Female,state2
32,"['Approach', 'None', 'Approach', 'None', 'Touc...","[4080, 32160, 2560, 7040, 5600, 7920, 2080, 17...",Adult,Female,state2
33,"['Approach', 'None', 'Approach', 'Follow', 'Ap...","[3840, 4960, 12880, 9440, 14080, 152240]",Adult,Male,state2
34,"['Approach', 'None', 'Touch', 'None', 'Touch',...","[12080, 2240, 2800, 30720, 4160, 8400, 3440, 1...",Child,Male,state2
35,"['Approach', 'None', 'Approach', 'Follow']","[4800, 17680, 1440, 4160]",Adult,Female,state2
36,"['Approach', 'None', 'Approach', 'None', 'Gest...","[10560, 8720, 3200, 5200, 4720, 12960, 17600]",Adult,Female,state2
37,"['Approach', 'None', 'Touch', 'None', 'Gesture...","[4320, 3760, 3920, 8640, 2080, 7040, 2320, 52960]",Adult,Female,state2
38,"['Approach', 'None', 'Touch', 'None', 'Gesture...","[5760, 26720, 5200, 16640, 3680, 160, 2960, 64...",Adult,Male,state2
39,"['Approach', 'None', 'Approach', 'None', 'Touc...","[15280, 4480, 1920, 3520, 24080, 1520, 7200]",Child,Male,state2
40,"['Approach', 'None', 'Touch', 'None', 'Approac...","[12240, 47120, 3680, 35840, 2480, 1920, 18000,...",Adult,Female,state2
41,"['Approach', 'None', 'Gesture', 'None', 'Appro...","[7680, 5200, 2800, 2400, 5360, 45360, 1840, 36...",Child,Male,state2

In [8]:
hidden_states = {'curious':dfs['state1'], 'attentive':dfs['state0'], 'engaged':dfs['state2']}

In [9]:
# 각 데이터프레임의 'A/C'와 'M/F' 열의 통계 출력
for sheet_name, df in hidden_states.items():
    print(f"Statistics for sheet '{sheet_name}':")
    print(df[['A/C', 'M/F']].describe())
    print()

Statistics for sheet 'curious':
          A/C   M/F
count     337   337
unique      2     2
top     Child  Male
freq      216   181

Statistics for sheet 'attentive':
          A/C   M/F
count     106   106
unique      2     2
top     Child  Male
freq       74    70

Statistics for sheet 'engaged':
          A/C   M/F
count      42    42
unique      2     2
top     Child  Male
freq       24    27

In [20]:
print("-----------------------")
print("        curious        ")
print("-----------------------")
print(hidden_states['curious']['A/C'].value_counts())
print()
print(hidden_states['curious']['M/F'].value_counts())
print()
print("Total:", len(hidden_states['curious']))

-----------------------
        curious
-----------------------
Child    216
Adult    121
Name: A/C, dtype: int64

Male      181
Female    156
Name: M/F, dtype: int64

Total: 337

In [26]:
print("-----------------------")
print("        curious        ")
print("-----------------------")
child_male_count = hidden_states['curious'].loc[(hidden_states['curious']['A/C'] == 'Child') & (hidden_states['curious']['M/F'] == 'Male')].shape[0]
child_female_count = hidden_states['curious'].loc[(hidden_states['curious']['A/C'] == 'Child') & (hidden_states['curious']['M/F'] == 'Female')].shape[0]
adult_male_count = hidden_states['curious'].loc[(hidden_states['curious']['A/C'] == 'Adult') & (hidden_states['curious']['M/F'] == 'Male')].shape[0]
adult_female_count = hidden_states['curious'].loc[(hidden_states['curious']['A/C'] == 'Adult') & (hidden_states['curious']['M/F'] == 'Female')].shape[0]

print("Child - Male:", child_male_count)
print("Child - Female:", child_female_count)
print("Adult - Male:", adult_male_count)
print("Adult - Female:", adult_female_count)

-----------------------
        curious
-----------------------
Child - Male: 132
Child - Female: 84
Adult - Male: 49
Adult - Female: 72

In [27]:
print("-----------------------")
print("       attentive       ")
print("-----------------------")
print(hidden_states['attentive']['A/C'].value_counts())
print()
print(hidden_states['attentive']['M/F'].value_counts())
print()
print("Total:", len(hidden_states['attentive']))

-----------------------
       attentive
-----------------------
Child    74
Adult    32
Name: A/C, dtype: int64

Male      70
Female    36
Name: M/F, dtype: int64

Total: 106

In [25]:
print("-----------------------")
print("       attentive       ")
print("-----------------------")
child_male_count = hidden_states['attentive'].loc[(hidden_states['attentive']['A/C'] == 'Child') & (hidden_states['attentive']['M/F'] == 'Male')].shape[0]
child_female_count = hidden_states['attentive'].loc[(hidden_states['attentive']['A/C'] == 'Child') & (hidden_states['attentive']['M/F'] == 'Female')].shape[0]
adult_male_count = hidden_states['attentive'].loc[(hidden_states['attentive']['A/C'] == 'Adult') & (hidden_states['attentive']['M/F'] == 'Male')].shape[0]
adult_female_count = hidden_states['attentive'].loc[(hidden_states['attentive']['A/C'] == 'Adult') & (hidden_states['attentive']['M/F'] == 'Female')].shape[0]

print("Child - Male:", child_male_count)
print("Child - Female:", child_female_count)
print("Adult - Male:", adult_male_count)
print("Adult - Female:", adult_female_count)

-----------------------
       attentive
-----------------------
Child - Male: 57
Child - Female: 17
Adult - Male: 13
Adult - Female: 19

In [22]:
print("-----------------------")
print("        engaged        ")
print("-----------------------")
print(hidden_states['engaged']['A/C'].value_counts())
print()
print(hidden_states['engaged']['M/F'].value_counts())
print()
print("Total:", len(hidden_states['engaged']))

-----------------------
        engaged
-----------------------
Child    24
Adult    18
Name: A/C, dtype: int64

Male      27
Female    15
Name: M/F, dtype: int64

Total: 42

In [24]:
print("-----------------------")
print("        engaged        ")
print("-----------------------")
child_male_count = hidden_states['engaged'].loc[(hidden_states['engaged']['A/C'] == 'Child') & (hidden_states['engaged']['M/F'] == 'Male')].shape[0]
child_female_count = hidden_states['engaged'].loc[(hidden_states['engaged']['A/C'] == 'Child') & (hidden_states['engaged']['M/F'] == 'Female')].shape[0]
adult_male_count = hidden_states['engaged'].loc[(hidden_states['engaged']['A/C'] == 'Adult') & (hidden_states['engaged']['M/F'] == 'Male')].shape[0]
adult_female_count = hidden_states['engaged'].loc[(hidden_states['engaged']['A/C'] == 'Adult') & (hidden_states['engaged']['M/F'] == 'Female')].shape[0]

print("Child - Male:", child_male_count)
print("Child - Female:", child_female_count)
print("Adult - Male:", adult_male_count)
print("Adult - Female:", adult_female_count)

-----------------------
        engaged
-----------------------
Child - Male: 17
Child - Female: 7
Adult - Male: 10
Adult - Female: 8